name: flutter_redux_dev_tools
description: A Time Traveling Redux Debugger for Flutter
version: 0.5.0
author: Brian Egan <brian@brianegan.com>
homepage: https://github.com/brianegan/flutter_redux_dev_tools

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ">=5.0.0 <6.0.0"
  redux_dev_tools: ">=0.7.0 <0.8.0"
  flutter_redux: ">=0.8.2 <0.9.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.11.0
  flutter_test:
    sdk: flutter

